# Generated by Django 6.0.2 on 2026-02-18 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(db_index=True, error_messages={'blank': 'Имя обязателено для заполнения', 'max_length': 'Имя не может быть больше 150 символов'}, help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(error_messages={'blank': 'Фамилия обязателена для заполнения', 'max_length': 'Фамилия не может быть больше 150 символов'}, help_text='Введите фамилию', max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, error_messages={'max_length': 'Отчество не может быть больше 150 символов'}, help_text='Введите отчество', max_length=150, verbose_name='Отчество')),
                ('email', models.EmailField(error_messages={'blank': 'Email обязателен для заполнения', 'invalid': 'Введите корректны Email (name@domain.com)', 'max_length': 'Email не может быть больше 254 символов', 'unique': 'Пользователь с таким email уже зарегестрирован'}, help_text='Введите Email', max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(error_messages={'blank': 'Телефон обязателен для заполнения', 'max_length': 'Слишком много символов', 'unique': 'Пользователь с таким телефоном уже зарегистрирован'}, help_text='Введите номер телефон', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Введите номер в формате: +79991234567 или 89991234567', regex='^\\+?7?\\d{10,15}$')], verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, error_messages={'invalid': 'Загрузите корректное изображение', 'invalid_image': 'Файл поврежден или не является изображением'}, help_text='Загрузите фото профиля', null=True, upload_to=users.utils.avater_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Разрешены только JPG, PNG')], verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
