# Generated by Django 6.0.2 on 2026-03-11 08:53

import django.core.validators
import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, error_messages={'blank': 'Поле не может быть пустым', 'max_length': 'Название не может быть больше 255 символов', 'unique': 'Такая  категория уже существует'}, help_text='Название категории', max_length=255)),
                ('icon', models.ImageField(blank=True, error_messages={'invalid': 'Загрузите корректное изображение', 'invalid_image': 'Файл поврежден или не является изображением'}, help_text='Иконка', null=True, upload_to=products.utils.category_icon_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Разрешены только JPG, PNG')], verbose_name='Иконка категории')),
                ('is_active', models.BooleanField(default=True, help_text='Категория активна')),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Категория удалена')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская категория', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
    ]
